### ISSUE TITLE
no methods pairs, keys, values?

### ISSUE THREAD

**Issue by stevengj** [scheinerman/Multisets.jl#1]
Seems like these methods could be handy, and could be implemented by falling through to the corresponding methods of the underlying `data::Dict`.   They make sense because you already have `getindex`.

(You could also replace `unique!(collect(m))` with `keys(m)` in the docs.)

**Comment by scheinerman** [comment]
This is a good idea. I'll try to get to this in the next week or so. Shouldn't be that hard as you point you. Thanks.

**Comment by scheinerman** [comment]
Hi. I added these methods (and updated the `README`). I just registered it so it may take a few minutes to wend its way through the system. Let me know if there's any problems. Thanks again for the suggestion.

**Comment by stevengj** [comment]
Thanks!
